# Generated by Django 3.2.3 on 2023-10-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsapplied',
            old_name='inrgredient',
            new_name='ingredient',
        ),
    ]
