# Generated by Django 3.2.3 on 2023-11-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('customuser', 'recipe'), name='favorite_constraints'),
        ),
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('customuser', 'recipe'), name='cart_constraints'),
        ),
    ]
