# Generated by Django 3.2.3 on 2023-10-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_inrgredient_ingredientsapplied_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsapplied',
            old_name='ingredient',
            new_name='inrgredient',
        ),
    ]
