# Generated by Django 3.2.3 on 2023-11-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231106_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsapplied',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ings_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
