# Generated by Django 3.2.3 on 2023-10-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231006_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_cart',
        ),
    ]
