# Generated by Django 3.2.3 on 2023-10-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredientsapplied_inrgredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsapplied',
            name='inrgredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientsapplied',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ings_recipe', to='recipes.recipe'),
        ),
    ]
