# Generated by Django 3.2.3 on 2023-11-08 16:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_alter_ingredientsapplied_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_favorite', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='recipes.recipe', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredientsapplied',
            name='amount',
            field=models.SmallIntegerField(help_text='значение должно быть 1 - 9999', validators=[django.core.validators.MinValueValidator(1, 'значение должно быть 1 - 9999'), django.core.validators.MaxValueValidator(1, 'значение должно быть 1 - 9999')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='значение должно быть 1 - 9999', validators=[django.core.validators.MinValueValidator(1, 'значение должно быть 1 - 9999'), django.core.validators.MaxValueValidator(9999, 'значение должно быть 1 - 9999')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientsApplied', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_carts', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
