# Generated by Django 3.2.3 on 2023-11-08 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20231108_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsapplied',
            name='amount',
            field=models.SmallIntegerField(help_text='значение должно быть 1 - 9999', validators=[django.core.validators.MinValueValidator(1, 'значение должно быть 1 - 9999'), django.core.validators.MaxValueValidator(9999, 'значение должно быть 1 - 9999')], verbose_name='Количество'),
        ),
    ]
