# Generated by Django 3.2.3 on 2023-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_shopping_cart_shoppingcart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='cart_constraints',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='customuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='customuser',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorite_constraints'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='cart_constraints'),
        ),
    ]
